name: main
on: [push, pull_request, workflow_dispatch]

jobs:
  make:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Lua and LuaRocks
        run: apt-get install lua5.2 luarocks

      - name: Make gamechain
        run: luarocks make --local gamechain-0.*.rockspec

      - name: Make gamechain-demo
        run: luarocks make --local gamechain-demo-*.rockspec
      
      - name: Install test runner
        run: luarocks install busted
      
      - name: Run tests
        run: busted -o utfTerminal
      
      - name: Run demo
        run: lua -l gamechain.demo -e ''
