name: main
on: [push, pull_request, workflow_dispatch]

jobs:
  make:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.2.4"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Make norn
        run: luarocks make --local norn-0.*.rockspec

      - name: Make norn-demo
        run: luarocks make --local norn-demo-*.rockspec
      
      - name: Install test runner
        run: luarocks install busted
      
      - name: Run tests
        run: busted --shuffle -o utfTerminal
      
      - name: Run demo
        run: lua -l norn.demo -e ''
